# Generated by Django 5.1.3 on 2024-11-10 23:44

from django.db import migrations

def seedProductos(apps, schema_editor):
    Producto = apps.get_model('base_app', 'Producto')

    Categoria = apps.get_model('base_app', 'Categoria')
    Marca = apps.get_model('base_app', 'Marca')
    Condicion_Producto = apps.get_model('base_app', 'Condicion_Producto')

    condiciones = [
        {'nom_cond': 'Nuevo'},
        {'nom_cond': 'Usado'},
        {'nom_cond': 'Reacondicionado'},
    ]
    for condicion in condiciones:
        Condicion_Producto.objects.create(**condicion)
        print(f'Condición {condicion["nom_cond"]} creada.')

    categorias = [
        {'nom_cate': 'Tecnologia'},
        {'nom_cate': 'Hardware'},
        {'nom_cate': 'Perifericos'},
        {'nom_cate': 'Otros'},
    ]
    for categoria in categorias:
        Categoria.objects.create(**categoria)
        print(f'Categoría {categoria["nom_cate"]} creada.')
    
    marcas = [
        {'nom_mar': 'Apple'},
        {'nom_mar': 'Samsung'},
        {'nom_mar': 'Xiaomi'},
        {'nom_mar': 'Huawei'},
    ]
    for marca in marcas:
        Marca.objects.create(**marca)
        print(f'Marca {marca["nom_mar"]} creada.')

    ## Todos los objetos de seed es nuevo 
    condicionNuevo = Condicion_Producto.objects.get(nom_cond="Nuevo")
    
    ## Deben haber de las 4 categorias
    categoriaTecnologia = Categoria.objects.get(nom_cate="Tecnologia")
    categoriaHardware = Categoria.objects.get(nom_cate="Hardware")
    categoriaPerifericos = Categoria.objects.get(nom_cate="Perifericos")
    categoriaOtros = Categoria.objects.get(nom_cate="Otros")

    ## Deben haber de varias marcas
    marcaApple = Marca.objects.get(nom_mar="Apple")
    marcaXiaomi = Marca.objects.get(nom_mar="Xiaomi")
    marcaHuawei = Marca.objects.get(nom_mar="Huawei")
    marcaSamsung = Marca.objects.get(nom_mar="Samsung")

    ## Creamos unos productos de tecnologia de ejemplo

    productosTecnologia = [ 
        {
          'nombre': 'iPhone 14 Pro Max',
          'descripcion': 'Lorem ipsum dolor sit amet, consectetur adipiscing.  ',
          'precio': 10000,
          'descuento': 0.2,
          'imagen': 'https://example.com/iphone-14-pro-max.jpg',
          'id_mar': marcaApple,
          'id_cate': categoriaTecnologia,
          'id_cond': condicionNuevo,  
        },
        {
            'nombre': 'Samsung Galaxy S21 Ultra',
            'descripcion': 'Lorem ipsum dolor sit amet, consectetur adipiscing.  ',
            'precio': 8000,
            'descuento': 0.1,
            'imagen': 'https://example.com/samsung-galaxy-s21-ultra.jpg',
            'id_mar': marcaSamsung,
            'id_cate': categoriaTecnologia,
            'id_cond': condicionNuevo,  
        },
        {
            'nombre': 'Huawei P40 Pro',
            'descripcion': 'Lorem ipsum dolor sit amenium condeserent',
            'precio': 6000,
            'descuento': 0.3,
            'imagen': 'https://example.com/huawei-p40-pro.jpg',
            'id_mar': marcaHuawei,
            'id_cate': categoriaTecnologia,
            'id_cond': condicionNuevo,  
        },
        {
            'nombre': 'Xiaomi Mi 11',
            'descripcion': 'Lorem ipsum dolor sit amet, consectetur adipiscing.  ',
            'precio': 5000,
            'descuento': 0.4,
            'imagen': 'https://example.com/xiaomi-mi-11.jpg',
            'id_mar': marcaXiaomi,
            'id_cate': categoriaTecnologia,
            'id_cond': condicionNuevo,
        }
    ]

    for producto in productosTecnologia:
        Producto.objects.create(**producto)
        print(f'Producto {producto["nombre"]} creado.')
    

    ## Creamos hardware de Apple y Samsung de Ejemplo
    productosHardware = [
        {
            'nombre': 'Macbook Pro M1 ',
            'descripcion': 'Lorem ipsum dolor sit amet, consectetur adipiscing.  ',
            'precio': 40000,
            'descuento': 0.2,
            'imagen': 'https://example.com/macbook-2.jpg',
            'id_mar': marcaApple,
            'id_cate': categoriaHardware,
            'id_cond': condicionNuevo,
        },
        {
            'nombre': 'samsung fullscreen',
            'descripcion': 'Lorem ipsum dolor sit amet, consectetur adipiscing.  ',
            'precio': 12000,
            'descuento': 0.2,
            'imagen': 'https://example.com/iphone-14-pro-max.jpg',
            'id_mar': marcaSamsung,
            'id_cate': categoriaHardware,
            'id_cond': condicionNuevo,
        }
    ]

    for producto in productosHardware:
        Producto.objects.create(**producto)
        print(f'Producto {producto["nombre"]} creado.')


    ## Creamos unos perifericos Huawei y Samsung de Ejemplo 

    productosPerifericos = [
        {
            'nombre': 'Huawei Watch 3',
            'descripcion': 'Lorem ipsum dolor sit amet, consectetur adipiscing.  ',
            'precio': 3000,
            'descuento': 0.1,
            'imagen': 'https://example.com/huawei-watch-3.jpg',
            'id_mar': marcaHuawei,
            'id_cate': categoriaPerifericos,
            'id_cond': condicionNuevo,
        },
        {
            'nombre': 'Samsung Galaxy Buds',
            'descripcion': 'Lorem ipsum dolor sit amet, consectetur adipiscing.  ',
            'precio': 2000,
            'descuento': 0.3,
            'imagen': 'https://example.com/samsung-galaxy-buds.jpg',
            'id_mar': marcaSamsung,
            'id_cate': categoriaPerifericos,
            'id_cond': condicionNuevo,
        }
    ]

    for producto in productosPerifericos:
        Producto.objects.create(**producto)
        print(f'Producto {producto["nombre"]} creado.')

    ## Creamos otros productos de ejemplo 

    productosOtros = [
        {
            'nombre': 'Smart TV Samsung UHD 4K',
            'descripcion': 'Lorem ipsum dolor sit amet, consectetur adipiscing.  ',
            'precio': 15000,
            'descuento': 0.1,
            'imagen': 'https://example.com/samsung-uhd-4k.jpg',
            'id_mar': marcaSamsung,
            'id_cate': categoriaOtros,
            'id_cond': condicionNuevo,
        },
        {
            'nombre': 'Smart Watch Apple Watch Series 6',
            'descripcion': 'Lorem ipsum dolor sit amet, consectetur adipiscing.  ',
            'precio': 10000,
            'descuento': 0.3,
            'imagen': 'https://example.com/apple-watch-series-6.jpg',
            'id_mar': marcaApple,
            'id_cate': categoriaOtros,
            'id_cond': condicionNuevo,
        },
    ]

    for producto in productosOtros:
        Producto.objects.create(**producto)
        print(f'Producto {producto["nombre"]} creado.')
    

    print('Seed de productos terminada correctamente')
    


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_categoria_comuna_condicion_producto_and_more'),
    ]

    operations = [
        migrations.RunPython(seedProductos),
    ]
