# Generated by Django 5.1 on 2024-11-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_nac',
        ),
    ]
